language: csharp
solution: Watchstander.sln

mono:
  - latest
  - alpha
  - beta
  - nightly

matrix:
  allow-failures:
    - mono: alpha
    - mono: beta
    - mono: nightly

install:
  - travis_retry nuget restore Watchstander.sln
  - travis_retry nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Watchstander.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./WatchstanderTests/bin/Release/WatchstanderTests.dll
